# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "4.8.4"
    - nodejs_version: "6.11.4"

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # Typical npm stuff.
  - md C:\nc
  - npm config set cache C:\nc
  - yarn add phantomjs-prebuilt
  - yarn install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - cmd: yarn test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
