# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Test against these versions of Node.js.
environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
  - yarn add mocha-appveyor-reporter
  # Output useful info for debugging.
  - node --version
  - yarn --version

# Post-install test scripts.
test_script:
  - git rev-parse HEAD
  - yarn test
  - yarn test:node

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
